-- Ops Hub schema: alerts for operational issues + event audit log.
-- Alerts are generated by scheduler jobs (delay detection, stuck tasks, crew shortages).
-- Event log captures ALL domain events from all services for audit/debugging.

CREATE TABLE alerts (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    alert_type  VARCHAR(50) NOT NULL
                CHECK (alert_type IN ('turnaround_delayed','task_stuck','crew_shortage','gate_conflict')),
    severity    VARCHAR(20) NOT NULL
                CHECK (severity IN ('info','warning','critical')),
    flight_id       VARCHAR(50),
    turnaround_id   VARCHAR(50),
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    status      VARCHAR(20) NOT NULL DEFAULT 'open'
                CHECK (status IN ('open','acknowledged','resolved','auto_resolved')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at TIMESTAMPTZ
);

CREATE TABLE event_log (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_type      VARCHAR(100) NOT NULL,
    source_service  VARCHAR(50) NOT NULL,
    payload         JSONB NOT NULL,
    received_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_alerts_status ON alerts(status);
CREATE INDEX idx_alerts_severity ON alerts(severity);
CREATE INDEX idx_alerts_created_at ON alerts(created_at);
CREATE INDEX idx_event_log_event_type ON event_log(event_type);
CREATE INDEX idx_event_log_received_at ON event_log(received_at);
